variables:
  bash_script_variable: "Bash Script Çalışıyor."
  docker_compose_variable: "Docker-Compose Çalışıyor."
  # name_surname => CI//CD ben eklediğim
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  
image: maven:latest  

stages:
    - bash_script
    - docker

cache:
  paths:
    - .m2/repository
    - target



bash_script_job:
  stage: bash_script 
  script: 
    - echo "$bash_script_variable"
    - ls -lab
    - ./project.sh
    - "mvn compile"

docker_compose_job:
  stage: docker 
  script: 
    - echo $docker_compose_variable"
    - pwd
    - ./project.sh
    - "mvn compile"
    - docker-compose up  # docker-compose -f deneme.docker-compose.yml up -d
