variables:
  bash_script_variable: "Bash Script Çalışıyor."
  docker_compose_variable: "Docker-Compose Çalışıyor."
  # name_surname => CI//CD ben eklediğim
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  
image: maven:latest  

stages:
    - bash_script
    - maven
    - docker

cache:
  paths:
    - .m2/repository
    - target

bash_script_job:
  stage: bash_script 
  script: 
    - echo "$bash_script_variable"
    - ls -lab
    - chmod 755 project.sh
    - ./project.sh 
 
maven_job:
  stage: maven
  script: 
    - echo "Maven "
    - "mvn compile"	

# before_script:
#   - docker info
#   - docker-compose --version  


  artifacts:
    paths:
      - documentation/api/dist


docker_compose_job:
  stage: docker 
  image: docker:17.06.0-ce
  services:
    - docker:17.06.0-ce-dind
  script: 
    - echo "$docker_compose_variable"
    - pwd
        # Install Docker Compose
    - install docker-compose    
    # - apk add --update py-pip &&
    #  pip install docker-compose
    # Generate api.html from the RAML format
    #- docker-compose --file docker-compose.helpers.yml run --rm api-documentation
    - docker-compose up  # docker-compose -f deneme.docker-compose.yml up -d
