
version: '3.1'

services:
  dailyapp:
    container_name: blog_react
    image: blog_react
    restart: always
    build: ./
    ports:
      - "5555:4444"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/blog?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    networks:
      - springmysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    ports:
      - 3306:3306
    expose:
      - "3306"

    networks:
      - springmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
      - MYSQL_USER=hamit
      - MYSQL_PASSWORD=root
    restart: unless-stopped

networks:
  springmysql:
    name: springmysql
    driver: bridge